### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by m4b** [kovvalsky/LangPro#1]
First command from readme has error: `source sink 'my_word_net' does not exist` from knowledge.pl

And `ccg_sen_d/SICK_trial_sen.pl` does not exist. 

Perhaps you forgot to commit them ?

**Comment by kovvalsky** [comment]
Thanks for your interest in LangPro.
You are right! I just added necessary files.
It should run without any problems by now.

**Comment by m4b** [comment]
Works as expected now, thanks! :)

This is very cool software, great work!
