### ISSUE TITLE
Want to know the naming convention in ccg_sen_d

### ISSUE THREAD

**Issue by masashi-y** [kovvalsky/LangPro#2]
Hi! Thank you for making public the codebase for your nice work!
I want to try running it and see the results with different parse inputs,
but I I can't see what are the difference among files in ccg_sen_d.
I thought SICK_trial_ccg.pl and SICK_trial_reccg.pl may be the same
(as these seem parse results of "rebanking" models,)
but through diff command these are different.
Could you add some info on the naming convention for these files??

Thank you in advance!

**Comment by kovvalsky** [comment]
Hi,
_d stands for a dot: every sentence ends with a dot. Surprisingly, a sentence with or without a dot can get different derivations.
_occg (old): C&C with non-rebanked models
_ccg: C&C with rebanked models
_eccg: EasyCCG with non-rebanked models
_reccg: EasyCCG with rebanked models
hope this helps

**Comment by masashi-y** [comment]
Thank you for the information!
Can I additionally ask why ccg_sen_d files for the SICK test data have "annotated" in their names?
Does this mean kind of gold or silver (the best ones chosen among N-bests) trees?

**Comment by kovvalsky** [comment]
Sick_test_annotated is an original name of the test portion of Sick which has gold answers. There is also Sick_test that has no answers inside.

**Comment by masashi-y** [comment]
Thank you!
