### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by zeidspex** [kovvalsky/LangPro#4]
I am trying to run the code on datasets other than SICK and FraCaS, however the documentation is scarce regarding to process of converting a dataset to the necessary format (eg. how do you get the files "SICK_trial_ccg.pl" and "SICK_trial_sen.pl" from "SICK_trial.txt").

Additional documentation is needed for the steps necessary to produce these files for any dataset.

**Comment by kovvalsky** [comment]
Hi @zeidspex, the colab notebook has detailed scripts that show how to convert SICK txt data into the expected prolog format:
https://colab.research.google.com/drive/10GjzWm6hO5yqjslYXrAjkasyM7L1s2B0?usp=sharing
source: https://naturallogic.pro/Teaching/esslli22/
