### ISSUE TITLE
API for individual and batch processing

### ISSUE THREAD

**Issue by aindilis** [kovvalsky/LangPro#5]
Hi,

I used esslli_langpro.py to go ahead and run LangPro on the SICK and FraCaS datasets.  Very nice, and very useful tool!

However, I was curious if there was an API for individual (and batch) processing, such as I assume is working for the demo here:

https://naturallogic.pro/LangPro/

I wasn't sure where to find code if available for the demo.

Also, it would be convenient if it had a Pengines server.

Before I set about trying to write this API, I thought I would ask, since the documentation appears not to have covered it.

Thank you,
Andrew

**Comment by kovvalsky** [comment]
Hi, thanks for trying out the prover.
The demo page uses a CGI script written in python that does more or less the same as what is in the notebook, and it is not an API.
The python script of the demo is not a part of the repo as it is outdated (the demo version hasn't been updated since 2017).
